apiVersion: v1
kind: Service
metadata:
  name: zachbot-go-service
  namespace: ollama
spec:
  selector:
    app: zachbot-go
  ports:
  - protocol: TCP
    port: 80
    targetPort: 6600
  type: ClusterIP
