apiVersion: v1
kind: Service
metadata:
  name: ollama-loadbalancer
  namespace: ollama
spec:
  type: LoadBalancer
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434         # Exposed port
      targetPort: 80       # Port on the pod/service

