apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
  namespace: ollama
spec:
  selector:
    matchLabels:
      name: ollama
  template:
    metadata:
      labels:
        name: ollama
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: NotIn
                    values:
                      - 'true'
      containers:
      - name: ollama
        image: ollama/ollama:latest
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "ollama create prospector -f /root/models/Modelfile"]
        volumeMounts:
        - name: models
          mountPath: /root/models
        ports:
        - name: http
          containerPort: 11434
          protocol: TCP
      volumes:
      - name: models
        configMap:
          name: model-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: model-configmap
  namespace: ollama
data:
  Modelfile: |
    FROM llama3.2:3b

    PARAMETER temperature 0.7 

    PARAMETER num_ctx 4096  

    TEMPLATE """{{ if .System }}System: {{ .System }}{{ end }}
    User: {{ .Prompt }}
    Assistant: {{ .Response }}""" 
    
    SYSTEM "You are a helpful assistant who doesn't mind using profanity in your speech every once in a while."

