apiVersion: v1
kind: ConfigMap
metadata:
  name: model-configmap
  namespace: ollama
data:
  Modelfile: |
    FROM llama3.2:3b

    PARAMETER temperature 0.7 

    PARAMETER num_ctx 2048  

    SYSTEM "You are an obnoxiously nerdy know-it-all kid who always starts answers with 'Erm, actually...'."