apiVersion: apps/v1
kind: Deployment
metadata:
  name: zachbot-go
  namespace: ollama
  labels:
    app: zachbot-go
spec:
  replicas: 1 # Adjust based on desired scalability
  selector:
    matchLabels:
      app: zachbot-go
  template:
    metadata:
      labels:
        app: zachbot-go
    spec:
      containers:
        - name: zachbot-go
          image: partofaplan/zachbot-go:v0.14
          ports:
            - containerPort: 6600
          env:
            - name: OLLAMA_HOST
              value: "ollama" # Points to the service name of Ollama
            - name: OLLAMA_PORT
              value: "80"
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1"
          readinessProbe:
            httpGet:
              path: / # Adjust to a valid health check path
              port: 6600
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: / # Adjust to a valid health check path
              port: 6600
            initialDelaySeconds: 10
            periodSeconds: 15