apiVersion: v1
kind: Service
metadata:
  name: zachbot-service
  namespace: ollama
  labels:
    app: zachbot
spec:
  selector:
    app: zachbot
  ports:
    - protocol: TCP
      port: 6500
      targetPort: 6500
  type: ClusterIP
