zachbot:
  replicaCount: 1
  image:
    repository: partofaplan/zachbot-go
    tag: v0.22
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: traefik
    host: zachbot.k3d.local
    path: /
    pathType: Prefix
    annotations: {}
  env:
    OLLAMA_HOST: zachbot-zachbot-ollama
    OLLAMA_PORT: "80"
    SERVER_PORT: "6600"
  resources:
    requests:
      memory: "128Mi"
      cpu: "500m"
    limits:
      memory: "256Mi"
      cpu: "1"

ollama:
  enabled: true
  image:
    repository: ollama/ollama
    tag: latest
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: traefik
    host: ollama.k3d.local
    path: /
    pathType: Prefix
    annotations: {}
  nodeAffinity:
    key: node-role.kubernetes.io/control-plane
    operator: NotIn
    values:
      - "true"
modelConfig:
  Modelfile: |
    FROM llama3.2:3b

    PARAMETER temperature 0.3
    PARAMETER top_k 40
    PARAMETER top_p 0.9
    PARAMETER repeat_penalty 1.1
    PARAMETER num_predict 200

    PARAMETER num_ctx 2048

    SYSTEM "You are ZachBot, an AI that provides accurate and concise answers. Prefer brevity: 2–5 sentences or short bullet points. Only elaborate when asked. Cite sources succinctly."
