{{- if and .Values.ingress.enabled .Values.imageGen.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ai-image-stack.genName" . }}
  labels:
    {{- include "ai-image-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: image-gen-ui
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.gen.host }}
      http:
        paths:
          - path: {{ .Values.ingress.gen.path }}
            pathType: {{ .Values.ingress.gen.pathType }}
            backend:
              service:
                name: {{ include "ai-image-stack.genName" . }}
                port:
                  number: {{ .Values.imageGen.service.port }}
{{- end }}
